DROP TABLE MEMBER;
DROP TABLE BOARD;

CREATE TABLE MEMBER(
  ID VARCHAR2(20),
  PW VARCHAR2(20) NOT NULL,
  EMAIL VARCHAR2(60) NOT NULL,
  WRITER VARCHAR2(20) NOT NULL,
  REGDATE DATE,
  "LEVEL" NUMBER,
);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY(ID);

CREATE TABLE BOARD (
  SEQ       NUMBER,
  ID        VARCHAR2(20) NOT NULL,
  WRITER    VARCHAR2(20) NOT NULL,
  TITLE     VARCHAR2(100) NOT NULL,
  CONTENT   VARCHAR2(4000) NOT NULL,
  "REF"     NUMBER       NOT NULL,
  STEP      NUMBER       NOT NULL,
  "DEPTH"   NUMBER       NOT NULL,
  READCOUNT NUMBER       NOT NULL,
  REGDATE   DATE         NOT NULL,
  DELFLAG   CHAR(1)      NOT NULL
);

ALTER TABLE BOARD
  ADD CONSTRAINT BOARD_PK PRIMARY KEY (SEQ);

ALTER TABLE BOARD
  ADD CONSTRAINT BOARD_FK FOREIGN KEY(ID) REFERENCES MEMBER(ID);

CREATE SEQUENCE BOARD_SEQ
  START WITH 1
  INCREMENT BY 1;
